// <auto-generated />
namespace FPFI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class zmanaskladnikówdoposiłków : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zmanaskladnikówdoposiłków));
        
        string IMigrationMetadata.Id
        {
            get { return "202306301855527_zmana skladników do posiłków"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
